<?php

namespace Rmunate\Calendario\Holidays\Colombia;

final class CO_2019
{
    /**
     * Returns the holidays for the year.
     *
     * @return array An array of holidays with detailed information.
     */
    public static function all()
    {
        return [
            [
                'year'           => 2019,
                'month'          => 1,
                'day'            => 1,
                'full_date'      => '2019-01-01',
                'day_of_year'    => 1,
                'iso_week'       => 1,
                'iso_day'        => 2,
                'holiday_reason' => 'Año Nuevo',
                'day_name'       => 'Tuesday',
                'month_name'     => 'January',
            ],
            [
                'year'           => 2019,
                'month'          => 1,
                'day'            => 6,
                'full_date'      => '2019-01-06',
                'day_of_year'    => 6,
                'iso_week'       => 1,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'January',
            ],
            [
                'year'           => 2019,
                'month'          => 1,
                'day'            => 7,
                'full_date'      => '2019-01-07',
                'day_of_year'    => 7,
                'iso_week'       => 2,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por el día de los Reyes Magos',
                'day_name'       => 'Monday',
                'month_name'     => 'January',
            ],
            [
                'year'           => 2019,
                'month'          => 1,
                'day'            => 13,
                'full_date'      => '2019-01-13',
                'day_of_year'    => 13,
                'iso_week'       => 2,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'January',
            ],
            [
                'year'           => 2019,
                'month'          => 1,
                'day'            => 20,
                'full_date'      => '2019-01-20',
                'day_of_year'    => 20,
                'iso_week'       => 3,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'January',
            ],
            [
                'year'           => 2019,
                'month'          => 1,
                'day'            => 27,
                'full_date'      => '2019-01-27',
                'day_of_year'    => 27,
                'iso_week'       => 4,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'January',
            ],
            [
                'year'           => 2019,
                'month'          => 2,
                'day'            => 3,
                'full_date'      => '2019-02-03',
                'day_of_year'    => 34,
                'iso_week'       => 5,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'February',
            ],
            [
                'year'           => 2019,
                'month'          => 2,
                'day'            => 10,
                'full_date'      => '2019-02-10',
                'day_of_year'    => 41,
                'iso_week'       => 6,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'February',
            ],
            [
                'year'           => 2019,
                'month'          => 2,
                'day'            => 17,
                'full_date'      => '2019-02-17',
                'day_of_year'    => 48,
                'iso_week'       => 7,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'February',
            ],
            [
                'year'           => 2019,
                'month'          => 2,
                'day'            => 24,
                'full_date'      => '2019-02-24',
                'day_of_year'    => 55,
                'iso_week'       => 8,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'February',
            ],
            [
                'year'           => 2019,
                'month'          => 3,
                'day'            => 3,
                'full_date'      => '2019-03-03',
                'day_of_year'    => 62,
                'iso_week'       => 9,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'March',
            ],
            [
                'year'           => 2019,
                'month'          => 3,
                'day'            => 10,
                'full_date'      => '2019-03-10',
                'day_of_year'    => 69,
                'iso_week'       => 10,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'March',
            ],
            [
                'year'           => 2019,
                'month'          => 3,
                'day'            => 17,
                'full_date'      => '2019-03-17',
                'day_of_year'    => 76,
                'iso_week'       => 11,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'March',
            ],
            [
                'year'           => 2019,
                'month'          => 3,
                'day'            => 24,
                'full_date'      => '2019-03-24',
                'day_of_year'    => 83,
                'iso_week'       => 12,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'March',
            ],
            [
                'year'           => 2019,
                'month'          => 3,
                'day'            => 25,
                'full_date'      => '2019-03-25',
                'day_of_year'    => 84,
                'iso_week'       => 13,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por el día de San José',
                'day_name'       => 'Monday',
                'month_name'     => 'March',
            ],
            [
                'year'           => 2019,
                'month'          => 3,
                'day'            => 31,
                'full_date'      => '2019-03-31',
                'day_of_year'    => 90,
                'iso_week'       => 13,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'March',
            ],
            [
                'year'           => 2019,
                'month'          => 4,
                'day'            => 7,
                'full_date'      => '2019-04-07',
                'day_of_year'    => 97,
                'iso_week'       => 14,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'April',
            ],
            [
                'year'           => 2019,
                'month'          => 4,
                'day'            => 14,
                'full_date'      => '2019-04-14',
                'day_of_year'    => 104,
                'iso_week'       => 15,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'April',
            ],
            [
                'year'           => 2019,
                'month'          => 4,
                'day'            => 18,
                'full_date'      => '2019-04-18',
                'day_of_year'    => 108,
                'iso_week'       => 16,
                'iso_day'        => 4,
                'holiday_reason' => 'Jueves Santo',
                'day_name'       => 'Thursday',
                'month_name'     => 'April',
            ],
            [
                'year'           => 2019,
                'month'          => 4,
                'day'            => 19,
                'full_date'      => '2019-04-19',
                'day_of_year'    => 109,
                'iso_week'       => 16,
                'iso_day'        => 5,
                'holiday_reason' => 'Viernes Santo',
                'day_name'       => 'Friday',
                'month_name'     => 'April',
            ],
            [
                'year'           => 2019,
                'month'          => 4,
                'day'            => 21,
                'full_date'      => '2019-04-21',
                'day_of_year'    => 111,
                'iso_week'       => 16,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'April',
            ],
            [
                'year'           => 2019,
                'month'          => 4,
                'day'            => 28,
                'full_date'      => '2019-04-28',
                'day_of_year'    => 118,
                'iso_week'       => 17,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'April',
            ],
            [
                'year'           => 2019,
                'month'          => 5,
                'day'            => 1,
                'full_date'      => '2019-05-01',
                'day_of_year'    => 121,
                'iso_week'       => 18,
                'iso_day'        => 3,
                'holiday_reason' => 'Día del trabajo',
                'day_name'       => 'Wednesday',
                'month_name'     => 'May',
            ],
            [
                'year'           => 2019,
                'month'          => 5,
                'day'            => 5,
                'full_date'      => '2019-05-05',
                'day_of_year'    => 125,
                'iso_week'       => 18,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'May',
            ],
            [
                'year'           => 2019,
                'month'          => 5,
                'day'            => 12,
                'full_date'      => '2019-05-12',
                'day_of_year'    => 132,
                'iso_week'       => 19,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'May',
            ],
            [
                'year'           => 2019,
                'month'          => 5,
                'day'            => 19,
                'full_date'      => '2019-05-19',
                'day_of_year'    => 139,
                'iso_week'       => 20,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'May',
            ],
            [
                'year'           => 2019,
                'month'          => 5,
                'day'            => 26,
                'full_date'      => '2019-05-26',
                'day_of_year'    => 146,
                'iso_week'       => 21,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'May',
            ],
            [
                'year'           => 2019,
                'month'          => 6,
                'day'            => 2,
                'full_date'      => '2019-06-02',
                'day_of_year'    => 153,
                'iso_week'       => 22,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'June',
            ],
            [
                'year'           => 2019,
                'month'          => 6,
                'day'            => 3,
                'full_date'      => '2019-06-03',
                'day_of_year'    => 154,
                'iso_week'       => 23,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por el Día de la Ascensión',
                'day_name'       => 'Monday',
                'month_name'     => 'June',
            ],
            [
                'year'           => 2019,
                'month'          => 6,
                'day'            => 9,
                'full_date'      => '2019-06-09',
                'day_of_year'    => 160,
                'iso_week'       => 23,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'June',
            ],
            [
                'year'           => 2019,
                'month'          => 6,
                'day'            => 16,
                'full_date'      => '2019-06-16',
                'day_of_year'    => 167,
                'iso_week'       => 24,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'June',
            ],
            [
                'year'           => 2019,
                'month'          => 6,
                'day'            => 23,
                'full_date'      => '2019-06-23',
                'day_of_year'    => 174,
                'iso_week'       => 25,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'June',
            ],
            [
                'year'           => 2019,
                'month'          => 6,
                'day'            => 24,
                'full_date'      => '2019-06-24',
                'day_of_year'    => 175,
                'iso_week'       => 26,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por el día de Corpus Christi',
                'day_name'       => 'Monday',
                'month_name'     => 'June',
            ],
            [
                'year'           => 2019,
                'month'          => 6,
                'day'            => 30,
                'full_date'      => '2019-06-30',
                'day_of_year'    => 181,
                'iso_week'       => 26,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'June',
            ],
            [
                'year'           => 2019,
                'month'          => 7,
                'day'            => 1,
                'full_date'      => '2019-07-01',
                'day_of_year'    => 182,
                'iso_week'       => 27,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por el día de San Pedro y San Pablo',
                'day_name'       => 'Monday',
                'month_name'     => 'July',
            ],
            [
                'year'           => 2019,
                'month'          => 7,
                'day'            => 7,
                'full_date'      => '2019-07-07',
                'day_of_year'    => 188,
                'iso_week'       => 27,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'July',
            ],
            [
                'year'           => 2019,
                'month'          => 7,
                'day'            => 14,
                'full_date'      => '2019-07-14',
                'day_of_year'    => 195,
                'iso_week'       => 28,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'July',
            ],
            [
                'year'           => 2019,
                'month'          => 7,
                'day'            => 20,
                'full_date'      => '2019-07-20',
                'day_of_year'    => 201,
                'iso_week'       => 29,
                'iso_day'        => 6,
                'holiday_reason' => 'Día de la independencia',
                'day_name'       => 'Saturday',
                'month_name'     => 'July',
            ],
            [
                'year'           => 2019,
                'month'          => 7,
                'day'            => 21,
                'full_date'      => '2019-07-21',
                'day_of_year'    => 202,
                'iso_week'       => 29,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'July',
            ],
            [
                'year'           => 2019,
                'month'          => 7,
                'day'            => 28,
                'full_date'      => '2019-07-28',
                'day_of_year'    => 209,
                'iso_week'       => 30,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'July',
            ],
            [
                'year'           => 2019,
                'month'          => 8,
                'day'            => 4,
                'full_date'      => '2019-08-04',
                'day_of_year'    => 216,
                'iso_week'       => 31,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'August',
            ],
            [
                'year'           => 2019,
                'month'          => 8,
                'day'            => 7,
                'full_date'      => '2019-08-07',
                'day_of_year'    => 219,
                'iso_week'       => 32,
                'iso_day'        => 3,
                'holiday_reason' => 'Batalla de Boyacá',
                'day_name'       => 'Wednesday',
                'month_name'     => 'August',
            ],
            [
                'year'           => 2019,
                'month'          => 8,
                'day'            => 11,
                'full_date'      => '2019-08-11',
                'day_of_year'    => 223,
                'iso_week'       => 32,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'August',
            ],
            [
                'year'           => 2019,
                'month'          => 8,
                'day'            => 18,
                'full_date'      => '2019-08-18',
                'day_of_year'    => 230,
                'iso_week'       => 33,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'August',
            ],
            [
                'year'           => 2019,
                'month'          => 8,
                'day'            => 19,
                'full_date'      => '2019-08-19',
                'day_of_year'    => 231,
                'iso_week'       => 34,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por la Asunción de la Virgen',
                'day_name'       => 'Monday',
                'month_name'     => 'August',
            ],
            [
                'year'           => 2019,
                'month'          => 8,
                'day'            => 25,
                'full_date'      => '2019-08-25',
                'day_of_year'    => 237,
                'iso_week'       => 34,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'August',
            ],
            [
                'year'           => 2019,
                'month'          => 9,
                'day'            => 1,
                'full_date'      => '2019-09-01',
                'day_of_year'    => 244,
                'iso_week'       => 35,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'September',
            ],
            [
                'year'           => 2019,
                'month'          => 9,
                'day'            => 8,
                'full_date'      => '2019-09-08',
                'day_of_year'    => 251,
                'iso_week'       => 36,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'September',
            ],
            [
                'year'           => 2019,
                'month'          => 9,
                'day'            => 15,
                'full_date'      => '2019-09-15',
                'day_of_year'    => 258,
                'iso_week'       => 37,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'September',
            ],
            [
                'year'           => 2019,
                'month'          => 9,
                'day'            => 22,
                'full_date'      => '2019-09-22',
                'day_of_year'    => 265,
                'iso_week'       => 38,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'September',
            ],
            [
                'year'           => 2019,
                'month'          => 9,
                'day'            => 29,
                'full_date'      => '2019-09-29',
                'day_of_year'    => 272,
                'iso_week'       => 39,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'September',
            ],
            [
                'year'           => 2019,
                'month'          => 10,
                'day'            => 6,
                'full_date'      => '2019-10-06',
                'day_of_year'    => 279,
                'iso_week'       => 40,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'October',
            ],
            [
                'year'           => 2019,
                'month'          => 10,
                'day'            => 13,
                'full_date'      => '2019-10-13',
                'day_of_year'    => 286,
                'iso_week'       => 41,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'October',
            ],
            [
                'year'           => 2019,
                'month'          => 10,
                'day'            => 14,
                'full_date'      => '2019-10-14',
                'day_of_year'    => 287,
                'iso_week'       => 42,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por el Día de la Raza',
                'day_name'       => 'Monday',
                'month_name'     => 'October',
            ],
            [
                'year'           => 2019,
                'month'          => 10,
                'day'            => 20,
                'full_date'      => '2019-10-20',
                'day_of_year'    => 293,
                'iso_week'       => 42,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'October',
            ],
            [
                'year'           => 2019,
                'month'          => 10,
                'day'            => 27,
                'full_date'      => '2019-10-27',
                'day_of_year'    => 300,
                'iso_week'       => 43,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'October',
            ],
            [
                'year'           => 2019,
                'month'          => 11,
                'day'            => 3,
                'full_date'      => '2019-11-03',
                'day_of_year'    => 307,
                'iso_week'       => 44,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'November',
            ],
            [
                'year'           => 2019,
                'month'          => 11,
                'day'            => 4,
                'full_date'      => '2019-11-04',
                'day_of_year'    => 308,
                'iso_week'       => 45,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por el día de todos los Santos',
                'day_name'       => 'Monday',
                'month_name'     => 'November',
            ],
            [
                'year'           => 2019,
                'month'          => 11,
                'day'            => 10,
                'full_date'      => '2019-11-10',
                'day_of_year'    => 314,
                'iso_week'       => 45,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'November',
            ],
            [
                'year'           => 2019,
                'month'          => 11,
                'day'            => 11,
                'full_date'      => '2019-11-11',
                'day_of_year'    => 315,
                'iso_week'       => 46,
                'iso_day'        => 1,
                'holiday_reason' => 'Festivo por la Independencia de Cartagena',
                'day_name'       => 'Monday',
                'month_name'     => 'November',
            ],
            [
                'year'           => 2019,
                'month'          => 11,
                'day'            => 17,
                'full_date'      => '2019-11-17',
                'day_of_year'    => 321,
                'iso_week'       => 46,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'November',
            ],
            [
                'year'           => 2019,
                'month'          => 11,
                'day'            => 24,
                'full_date'      => '2019-11-24',
                'day_of_year'    => 328,
                'iso_week'       => 47,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'November',
            ],
            [
                'year'           => 2019,
                'month'          => 12,
                'day'            => 1,
                'full_date'      => '2019-12-01',
                'day_of_year'    => 335,
                'iso_week'       => 48,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'December',
            ],
            [
                'year'           => 2019,
                'month'          => 12,
                'day'            => 8,
                'full_date'      => '2019-12-08',
                'day_of_year'    => 342,
                'iso_week'       => 49,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'December',
            ],
            [
                'year'           => 2019,
                'month'          => 12,
                'day'            => 15,
                'full_date'      => '2019-12-15',
                'day_of_year'    => 349,
                'iso_week'       => 50,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'December',
            ],
            [
                'year'           => 2019,
                'month'          => 12,
                'day'            => 22,
                'full_date'      => '2019-12-22',
                'day_of_year'    => 356,
                'iso_week'       => 51,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'December',
            ],
            [
                'year'           => 2019,
                'month'          => 12,
                'day'            => 25,
                'full_date'      => '2019-12-25',
                'day_of_year'    => 359,
                'iso_week'       => 52,
                'iso_day'        => 3,
                'holiday_reason' => 'Navidad',
                'day_name'       => 'Wednesday',
                'month_name'     => 'December',
            ],
            [
                'year'           => 2019,
                'month'          => 12,
                'day'            => 29,
                'full_date'      => '2019-12-29',
                'day_of_year'    => 363,
                'iso_week'       => 52,
                'iso_day'        => 7,
                'holiday_reason' => 'Día Domingo Festivo',
                'day_name'       => 'Sunday',
                'month_name'     => 'December',
            ],
        ];
    }
}
