<?php

namespace Rmunate\Calendario\Holidays\Colombia;

final class CO_2032
{
    /**
     * Returns the holidays for the year.
     *
     * @return array An array of holidays with detailed information.
     */
    public static function all()
    {
        return [
            [
                "year" => 2032,
                "month" => 1,
                "day" => 1,
                "full_date" => "2032-01-01",
                "day_of_year" => 1,
                "iso_week" => 1,
                "iso_day" => 4,
                "holiday_reason" => "Año Nuevo",
                "day_name" => "Thursday",
                "month_name" => "January"
            ],
            [
                "year" => 2032,
                "month" => 1,
                "day" => 4,
                "full_date" => "2032-01-04",
                "day_of_year" => 4,
                "iso_week" => 1,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2032,
                "month" => 1,
                "day" => 11,
                "full_date" => "2032-01-11",
                "day_of_year" => 11,
                "iso_week" => 2,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2032,
                "month" => 1,
                "day" => 12,
                "full_date" => "2032-01-12",
                "day_of_year" => 12,
                "iso_week" => 3,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de los Reyes Magos",
                "day_name" => "Monday",
                "month_name" => "January"
            ],
            [
                "year" => 2032,
                "month" => 1,
                "day" => 18,
                "full_date" => "2032-01-18",
                "day_of_year" => 18,
                "iso_week" => 3,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2032,
                "month" => 1,
                "day" => 25,
                "full_date" => "2032-01-25",
                "day_of_year" => 25,
                "iso_week" => 4,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2032,
                "month" => 2,
                "day" => 1,
                "full_date" => "2032-02-01",
                "day_of_year" => 32,
                "iso_week" => 5,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2032,
                "month" => 2,
                "day" => 8,
                "full_date" => "2032-02-08",
                "day_of_year" => 39,
                "iso_week" => 6,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2032,
                "month" => 2,
                "day" => 15,
                "full_date" => "2032-02-15",
                "day_of_year" => 46,
                "iso_week" => 7,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2032,
                "month" => 2,
                "day" => 22,
                "full_date" => "2032-02-22",
                "day_of_year" => 53,
                "iso_week" => 8,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2032,
                "month" => 2,
                "day" => 29,
                "full_date" => "2032-02-29",
                "day_of_year" => 60,
                "iso_week" => 9,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2032,
                "month" => 3,
                "day" => 7,
                "full_date" => "2032-03-07",
                "day_of_year" => 67,
                "iso_week" => 10,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "March"
            ],
            [
                "year" => 2032,
                "month" => 3,
                "day" => 14,
                "full_date" => "2032-03-14",
                "day_of_year" => 74,
                "iso_week" => 11,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "March"
            ],
            [
                "year" => 2032,
                "month" => 3,
                "day" => 21,
                "full_date" => "2032-03-21",
                "day_of_year" => 81,
                "iso_week" => 12,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "March"
            ],
            [
                "year" => 2032,
                "month" => 3,
                "day" => 22,
                "full_date" => "2032-03-22",
                "day_of_year" => 82,
                "iso_week" => 13,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de San José",
                "day_name" => "Monday",
                "month_name" => "March"
            ],
            [
                "year" => 2032,
                "month" => 3,
                "day" => 25,
                "full_date" => "2032-03-25",
                "day_of_year" => 85,
                "iso_week" => 13,
                "iso_day" => 4,
                "holiday_reason" => "Jueves Santo",
                "day_name" => "Thursday",
                "month_name" => "March"
            ],
            [
                "year" => 2032,
                "month" => 3,
                "day" => 26,
                "full_date" => "2032-03-26",
                "day_of_year" => 86,
                "iso_week" => 13,
                "iso_day" => 5,
                "holiday_reason" => "Viernes Santo",
                "day_name" => "Friday",
                "month_name" => "March"
            ],
            [
                "year" => 2032,
                "month" => 3,
                "day" => 28,
                "full_date" => "2032-03-28",
                "day_of_year" => 88,
                "iso_week" => 13,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "March"
            ],
            [
                "year" => 2032,
                "month" => 4,
                "day" => 4,
                "full_date" => "2032-04-04",
                "day_of_year" => 95,
                "iso_week" => 14,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "April"
            ],
            [
                "year" => 2032,
                "month" => 4,
                "day" => 11,
                "full_date" => "2032-04-11",
                "day_of_year" => 102,
                "iso_week" => 15,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "April"
            ],
            [
                "year" => 2032,
                "month" => 4,
                "day" => 18,
                "full_date" => "2032-04-18",
                "day_of_year" => 109,
                "iso_week" => 16,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "April"
            ],
            [
                "year" => 2032,
                "month" => 4,
                "day" => 25,
                "full_date" => "2032-04-25",
                "day_of_year" => 116,
                "iso_week" => 17,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "April"
            ],
            [
                "year" => 2032,
                "month" => 5,
                "day" => 1,
                "full_date" => "2032-05-01",
                "day_of_year" => 122,
                "iso_week" => 18,
                "iso_day" => 6,
                "holiday_reason" => "Día del trabajo",
                "day_name" => "Saturday",
                "month_name" => "May"
            ],
            [
                "year" => 2032,
                "month" => 5,
                "day" => 2,
                "full_date" => "2032-05-02",
                "day_of_year" => 123,
                "iso_week" => 18,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2032,
                "month" => 5,
                "day" => 9,
                "full_date" => "2032-05-09",
                "day_of_year" => 130,
                "iso_week" => 19,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2032,
                "month" => 5,
                "day" => 10,
                "full_date" => "2032-05-10",
                "day_of_year" => 131,
                "iso_week" => 20,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el Día de la Ascensión",
                "day_name" => "Monday",
                "month_name" => "May"
            ],
            [
                "year" => 2032,
                "month" => 5,
                "day" => 16,
                "full_date" => "2032-05-16",
                "day_of_year" => 137,
                "iso_week" => 20,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2032,
                "month" => 5,
                "day" => 23,
                "full_date" => "2032-05-23",
                "day_of_year" => 144,
                "iso_week" => 21,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2032,
                "month" => 5,
                "day" => 30,
                "full_date" => "2032-05-30",
                "day_of_year" => 151,
                "iso_week" => 22,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2032,
                "month" => 5,
                "day" => 31,
                "full_date" => "2032-05-31",
                "day_of_year" => 152,
                "iso_week" => 23,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de Corpus Christi",
                "day_name" => "Monday",
                "month_name" => "May"
            ],
            [
                "year" => 2032,
                "month" => 6,
                "day" => 6,
                "full_date" => "2032-06-06",
                "day_of_year" => 158,
                "iso_week" => 23,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "June"
            ],
            [
                "year" => 2032,
                "month" => 6,
                "day" => 7,
                "full_date" => "2032-06-07",
                "day_of_year" => 159,
                "iso_week" => 24,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día del Sagrado Corazón de Jesús",
                "day_name" => "Monday",
                "month_name" => "June"
            ],
            [
                "year" => 2032,
                "month" => 6,
                "day" => 13,
                "full_date" => "2032-06-13",
                "day_of_year" => 165,
                "iso_week" => 24,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "June"
            ],
            [
                "year" => 2032,
                "month" => 6,
                "day" => 20,
                "full_date" => "2032-06-20",
                "day_of_year" => 172,
                "iso_week" => 25,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "June"
            ],
            [
                "year" => 2032,
                "month" => 6,
                "day" => 27,
                "full_date" => "2032-06-27",
                "day_of_year" => 179,
                "iso_week" => 26,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "June"
            ],
            [
                "year" => 2032,
                "month" => 7,
                "day" => 4,
                "full_date" => "2032-07-04",
                "day_of_year" => 186,
                "iso_week" => 27,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2032,
                "month" => 7,
                "day" => 5,
                "full_date" => "2032-07-05",
                "day_of_year" => 187,
                "iso_week" => 28,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de San Pedro y San Pablo",
                "day_name" => "Monday",
                "month_name" => "July"
            ],
            [
                "year" => 2032,
                "month" => 7,
                "day" => 11,
                "full_date" => "2032-07-11",
                "day_of_year" => 193,
                "iso_week" => 28,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2032,
                "month" => 7,
                "day" => 18,
                "full_date" => "2032-07-18",
                "day_of_year" => 200,
                "iso_week" => 29,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2032,
                "month" => 7,
                "day" => 20,
                "full_date" => "2032-07-20",
                "day_of_year" => 202,
                "iso_week" => 30,
                "iso_day" => 2,
                "holiday_reason" => "Día de la independencia",
                "day_name" => "Tuesday",
                "month_name" => "July"
            ],
            [
                "year" => 2032,
                "month" => 7,
                "day" => 25,
                "full_date" => "2032-07-25",
                "day_of_year" => 207,
                "iso_week" => 30,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2032,
                "month" => 8,
                "day" => 1,
                "full_date" => "2032-08-01",
                "day_of_year" => 214,
                "iso_week" => 31,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2032,
                "month" => 8,
                "day" => 7,
                "full_date" => "2032-08-07",
                "day_of_year" => 220,
                "iso_week" => 32,
                "iso_day" => 6,
                "holiday_reason" => "Batalla de Boyacá",
                "day_name" => "Saturday",
                "month_name" => "August"
            ],
            [
                "year" => 2032,
                "month" => 8,
                "day" => 8,
                "full_date" => "2032-08-08",
                "day_of_year" => 221,
                "iso_week" => 32,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2032,
                "month" => 8,
                "day" => 15,
                "full_date" => "2032-08-15",
                "day_of_year" => 228,
                "iso_week" => 33,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2032,
                "month" => 8,
                "day" => 16,
                "full_date" => "2032-08-16",
                "day_of_year" => 229,
                "iso_week" => 34,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por la Asunción de la Virgen",
                "day_name" => "Monday",
                "month_name" => "August"
            ],
            [
                "year" => 2032,
                "month" => 8,
                "day" => 22,
                "full_date" => "2032-08-22",
                "day_of_year" => 235,
                "iso_week" => 34,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2032,
                "month" => 8,
                "day" => 29,
                "full_date" => "2032-08-29",
                "day_of_year" => 242,
                "iso_week" => 35,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2032,
                "month" => 9,
                "day" => 5,
                "full_date" => "2032-09-05",
                "day_of_year" => 249,
                "iso_week" => 36,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "September"
            ],
            [
                "year" => 2032,
                "month" => 9,
                "day" => 12,
                "full_date" => "2032-09-12",
                "day_of_year" => 256,
                "iso_week" => 37,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "September"
            ],
            [
                "year" => 2032,
                "month" => 9,
                "day" => 19,
                "full_date" => "2032-09-19",
                "day_of_year" => 263,
                "iso_week" => 38,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "September"
            ],
            [
                "year" => 2032,
                "month" => 9,
                "day" => 26,
                "full_date" => "2032-09-26",
                "day_of_year" => 270,
                "iso_week" => 39,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "September"
            ],
            [
                "year" => 2032,
                "month" => 10,
                "day" => 3,
                "full_date" => "2032-10-03",
                "day_of_year" => 277,
                "iso_week" => 40,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2032,
                "month" => 10,
                "day" => 10,
                "full_date" => "2032-10-10",
                "day_of_year" => 284,
                "iso_week" => 41,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2032,
                "month" => 10,
                "day" => 17,
                "full_date" => "2032-10-17",
                "day_of_year" => 291,
                "iso_week" => 42,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2032,
                "month" => 10,
                "day" => 18,
                "full_date" => "2032-10-18",
                "day_of_year" => 292,
                "iso_week" => 43,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el Día de la Raza",
                "day_name" => "Monday",
                "month_name" => "October"
            ],
            [
                "year" => 2032,
                "month" => 10,
                "day" => 24,
                "full_date" => "2032-10-24",
                "day_of_year" => 298,
                "iso_week" => 43,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2032,
                "month" => 10,
                "day" => 31,
                "full_date" => "2032-10-31",
                "day_of_year" => 305,
                "iso_week" => 44,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2032,
                "month" => 11,
                "day" => 1,
                "full_date" => "2032-11-01",
                "day_of_year" => 306,
                "iso_week" => 45,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de todos los Santos",
                "day_name" => "Monday",
                "month_name" => "November"
            ],
            [
                "year" => 2032,
                "month" => 11,
                "day" => 7,
                "full_date" => "2032-11-07",
                "day_of_year" => 312,
                "iso_week" => 45,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "November"
            ],
            [
                "year" => 2032,
                "month" => 11,
                "day" => 14,
                "full_date" => "2032-11-14",
                "day_of_year" => 319,
                "iso_week" => 46,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "November"
            ],
            [
                "year" => 2032,
                "month" => 11,
                "day" => 15,
                "full_date" => "2032-11-15",
                "day_of_year" => 320,
                "iso_week" => 47,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por la Independencia de Cartagena",
                "day_name" => "Monday",
                "month_name" => "November"
            ],
            [
                "year" => 2032,
                "month" => 11,
                "day" => 21,
                "full_date" => "2032-11-21",
                "day_of_year" => 326,
                "iso_week" => 47,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "November"
            ],
            [
                "year" => 2032,
                "month" => 11,
                "day" => 28,
                "full_date" => "2032-11-28",
                "day_of_year" => 333,
                "iso_week" => 48,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "November"
            ],
            [
                "year" => 2032,
                "month" => 12,
                "day" => 5,
                "full_date" => "2032-12-05",
                "day_of_year" => 340,
                "iso_week" => 49,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "December"
            ],
            [
                "year" => 2032,
                "month" => 12,
                "day" => 8,
                "full_date" => "2032-12-08",
                "day_of_year" => 343,
                "iso_week" => 50,
                "iso_day" => 3,
                "holiday_reason" => "Inmaculada Concepción",
                "day_name" => "Wednesday",
                "month_name" => "December"
            ],
            [
                "year" => 2032,
                "month" => 12,
                "day" => 12,
                "full_date" => "2032-12-12",
                "day_of_year" => 347,
                "iso_week" => 50,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "December"
            ],
            [
                "year" => 2032,
                "month" => 12,
                "day" => 19,
                "full_date" => "2032-12-19",
                "day_of_year" => 354,
                "iso_week" => 51,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "December"
            ],
            [
                "year" => 2032,
                "month" => 12,
                "day" => 25,
                "full_date" => "2032-12-25",
                "day_of_year" => 360,
                "iso_week" => 52,
                "iso_day" => 6,
                "holiday_reason" => "Navidad",
                "day_name" => "Saturday",
                "month_name" => "December"
            ],
            [
                "year" => 2032,
                "month" => 12,
                "day" => 26,
                "full_date" => "2032-12-26",
                "day_of_year" => 361,
                "iso_week" => 52,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "December"
            ]
        ];
    }
}