<?php

namespace Rmunate\Calendario\Holidays\Colombia;

final class CO_2016
{
    /**
     * Returns the holidays for the year.
     *
     * @return array An array of holidays with detailed information.
     */
    public static function all()
    {
        return [
            [
                "year" => 2016,
                "month" => 1,
                "day" => 1,
                "full_date" => "2016-01-01",
                "day_of_year" => 1,
                "iso_week" => 53,
                "iso_day" => 5,
                "holiday_reason" => "Año Nuevo",
                "day_name" => "Friday",
                "month_name" => "January"
            ],
            [
                "year" => 2016,
                "month" => 1,
                "day" => 3,
                "full_date" => "2016-01-03",
                "day_of_year" => 3,
                "iso_week" => 53,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2016,
                "month" => 1,
                "day" => 10,
                "full_date" => "2016-01-10",
                "day_of_year" => 10,
                "iso_week" => 1,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2016,
                "month" => 1,
                "day" => 11,
                "full_date" => "2016-01-11",
                "day_of_year" => 11,
                "iso_week" => 2,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de los Reyes Magos",
                "day_name" => "Monday",
                "month_name" => "January"
            ],
            [
                "year" => 2016,
                "month" => 1,
                "day" => 17,
                "full_date" => "2016-01-17",
                "day_of_year" => 17,
                "iso_week" => 2,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2016,
                "month" => 1,
                "day" => 24,
                "full_date" => "2016-01-24",
                "day_of_year" => 24,
                "iso_week" => 3,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2016,
                "month" => 1,
                "day" => 31,
                "full_date" => "2016-01-31",
                "day_of_year" => 31,
                "iso_week" => 4,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "January"
            ],
            [
                "year" => 2016,
                "month" => 2,
                "day" => 7,
                "full_date" => "2016-02-07",
                "day_of_year" => 38,
                "iso_week" => 5,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2016,
                "month" => 2,
                "day" => 14,
                "full_date" => "2016-02-14",
                "day_of_year" => 45,
                "iso_week" => 6,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2016,
                "month" => 2,
                "day" => 21,
                "full_date" => "2016-02-21",
                "day_of_year" => 52,
                "iso_week" => 7,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2016,
                "month" => 2,
                "day" => 28,
                "full_date" => "2016-02-28",
                "day_of_year" => 59,
                "iso_week" => 8,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "February"
            ],
            [
                "year" => 2016,
                "month" => 3,
                "day" => 6,
                "full_date" => "2016-03-06",
                "day_of_year" => 66,
                "iso_week" => 9,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "March"
            ],
            [
                "year" => 2016,
                "month" => 3,
                "day" => 13,
                "full_date" => "2016-03-13",
                "day_of_year" => 73,
                "iso_week" => 10,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "March"
            ],
            [
                "year" => 2016,
                "month" => 3,
                "day" => 20,
                "full_date" => "2016-03-20",
                "day_of_year" => 80,
                "iso_week" => 11,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "March"
            ],
            [
                "year" => 2016,
                "month" => 3,
                "day" => 21,
                "full_date" => "2016-03-21",
                "day_of_year" => 81,
                "iso_week" => 12,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de San José",
                "day_name" => "Monday",
                "month_name" => "March"
            ],
            [
                "year" => 2016,
                "month" => 3,
                "day" => 24,
                "full_date" => "2016-03-24",
                "day_of_year" => 84,
                "iso_week" => 12,
                "iso_day" => 4,
                "holiday_reason" => "Jueves Santo",
                "day_name" => "Thursday",
                "month_name" => "March"
            ],
            [
                "year" => 2016,
                "month" => 3,
                "day" => 25,
                "full_date" => "2016-03-25",
                "day_of_year" => 85,
                "iso_week" => 12,
                "iso_day" => 5,
                "holiday_reason" => "Viernes Santo",
                "day_name" => "Friday",
                "month_name" => "March"
            ],
            [
                "year" => 2016,
                "month" => 3,
                "day" => 27,
                "full_date" => "2016-03-27",
                "day_of_year" => 87,
                "iso_week" => 12,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "March"
            ],
            [
                "year" => 2016,
                "month" => 4,
                "day" => 3,
                "full_date" => "2016-04-03",
                "day_of_year" => 94,
                "iso_week" => 13,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "April"
            ],
            [
                "year" => 2016,
                "month" => 4,
                "day" => 10,
                "full_date" => "2016-04-10",
                "day_of_year" => 101,
                "iso_week" => 14,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "April"
            ],
            [
                "year" => 2016,
                "month" => 4,
                "day" => 17,
                "full_date" => "2016-04-17",
                "day_of_year" => 108,
                "iso_week" => 15,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "April"
            ],
            [
                "year" => 2016,
                "month" => 4,
                "day" => 24,
                "full_date" => "2016-04-24",
                "day_of_year" => 115,
                "iso_week" => 16,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "April"
            ],
            [
                "year" => 2016,
                "month" => 5,
                "day" => 1,
                "full_date" => "2016-05-01",
                "day_of_year" => 122,
                "iso_week" => 17,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2016,
                "month" => 5,
                "day" => 8,
                "full_date" => "2016-05-08",
                "day_of_year" => 129,
                "iso_week" => 18,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2016,
                "month" => 5,
                "day" => 9,
                "full_date" => "2016-05-09",
                "day_of_year" => 130,
                "iso_week" => 19,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el Día de la Ascensión",
                "day_name" => "Monday",
                "month_name" => "May"
            ],
            [
                "year" => 2016,
                "month" => 5,
                "day" => 15,
                "full_date" => "2016-05-15",
                "day_of_year" => 136,
                "iso_week" => 19,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2016,
                "month" => 5,
                "day" => 22,
                "full_date" => "2016-05-22",
                "day_of_year" => 143,
                "iso_week" => 20,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2016,
                "month" => 5,
                "day" => 29,
                "full_date" => "2016-05-29",
                "day_of_year" => 150,
                "iso_week" => 21,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "May"
            ],
            [
                "year" => 2016,
                "month" => 5,
                "day" => 30,
                "full_date" => "2016-05-30",
                "day_of_year" => 151,
                "iso_week" => 22,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de Corpus Christi",
                "day_name" => "Monday",
                "month_name" => "May"
            ],
            [
                "year" => 2016,
                "month" => 6,
                "day" => 5,
                "full_date" => "2016-06-05",
                "day_of_year" => 157,
                "iso_week" => 22,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "June"
            ],
            [
                "year" => 2016,
                "month" => 6,
                "day" => 6,
                "full_date" => "2016-06-06",
                "day_of_year" => 158,
                "iso_week" => 23,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día del Sagrado Corazón de Jesús",
                "day_name" => "Monday",
                "month_name" => "June"
            ],
            [
                "year" => 2016,
                "month" => 6,
                "day" => 12,
                "full_date" => "2016-06-12",
                "day_of_year" => 164,
                "iso_week" => 23,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "June"
            ],
            [
                "year" => 2016,
                "month" => 6,
                "day" => 19,
                "full_date" => "2016-06-19",
                "day_of_year" => 171,
                "iso_week" => 24,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "June"
            ],
            [
                "year" => 2016,
                "month" => 6,
                "day" => 26,
                "full_date" => "2016-06-26",
                "day_of_year" => 178,
                "iso_week" => 25,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "June"
            ],
            [
                "year" => 2016,
                "month" => 7,
                "day" => 3,
                "full_date" => "2016-07-03",
                "day_of_year" => 185,
                "iso_week" => 26,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2016,
                "month" => 7,
                "day" => 4,
                "full_date" => "2016-07-04",
                "day_of_year" => 186,
                "iso_week" => 27,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de San Pedro y San Pablo",
                "day_name" => "Monday",
                "month_name" => "July"
            ],
            [
                "year" => 2016,
                "month" => 7,
                "day" => 10,
                "full_date" => "2016-07-10",
                "day_of_year" => 192,
                "iso_week" => 27,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2016,
                "month" => 7,
                "day" => 17,
                "full_date" => "2016-07-17",
                "day_of_year" => 199,
                "iso_week" => 28,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2016,
                "month" => 7,
                "day" => 20,
                "full_date" => "2016-07-20",
                "day_of_year" => 202,
                "iso_week" => 29,
                "iso_day" => 3,
                "holiday_reason" => "Día de la independencia",
                "day_name" => "Wednesday",
                "month_name" => "July"
            ],
            [
                "year" => 2016,
                "month" => 7,
                "day" => 24,
                "full_date" => "2016-07-24",
                "day_of_year" => 206,
                "iso_week" => 29,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2016,
                "month" => 7,
                "day" => 31,
                "full_date" => "2016-07-31",
                "day_of_year" => 213,
                "iso_week" => 30,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "July"
            ],
            [
                "year" => 2016,
                "month" => 8,
                "day" => 7,
                "full_date" => "2016-08-07",
                "day_of_year" => 220,
                "iso_week" => 31,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2016,
                "month" => 8,
                "day" => 14,
                "full_date" => "2016-08-14",
                "day_of_year" => 227,
                "iso_week" => 32,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2016,
                "month" => 8,
                "day" => 15,
                "full_date" => "2016-08-15",
                "day_of_year" => 228,
                "iso_week" => 33,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por la Asunción de la Virgen",
                "day_name" => "Monday",
                "month_name" => "August"
            ],
            [
                "year" => 2016,
                "month" => 8,
                "day" => 21,
                "full_date" => "2016-08-21",
                "day_of_year" => 234,
                "iso_week" => 33,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2016,
                "month" => 8,
                "day" => 28,
                "full_date" => "2016-08-28",
                "day_of_year" => 241,
                "iso_week" => 34,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "August"
            ],
            [
                "year" => 2016,
                "month" => 9,
                "day" => 4,
                "full_date" => "2016-09-04",
                "day_of_year" => 248,
                "iso_week" => 35,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "September"
            ],
            [
                "year" => 2016,
                "month" => 9,
                "day" => 11,
                "full_date" => "2016-09-11",
                "day_of_year" => 255,
                "iso_week" => 36,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "September"
            ],
            [
                "year" => 2016,
                "month" => 9,
                "day" => 18,
                "full_date" => "2016-09-18",
                "day_of_year" => 262,
                "iso_week" => 37,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "September"
            ],
            [
                "year" => 2016,
                "month" => 9,
                "day" => 25,
                "full_date" => "2016-09-25",
                "day_of_year" => 269,
                "iso_week" => 38,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "September"
            ],
            [
                "year" => 2016,
                "month" => 10,
                "day" => 2,
                "full_date" => "2016-10-02",
                "day_of_year" => 276,
                "iso_week" => 39,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2016,
                "month" => 10,
                "day" => 9,
                "full_date" => "2016-10-09",
                "day_of_year" => 283,
                "iso_week" => 40,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2016,
                "month" => 10,
                "day" => 16,
                "full_date" => "2016-10-16",
                "day_of_year" => 290,
                "iso_week" => 41,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2016,
                "month" => 10,
                "day" => 17,
                "full_date" => "2016-10-17",
                "day_of_year" => 291,
                "iso_week" => 42,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el Día de la Raza",
                "day_name" => "Monday",
                "month_name" => "October"
            ],
            [
                "year" => 2016,
                "month" => 10,
                "day" => 23,
                "full_date" => "2016-10-23",
                "day_of_year" => 297,
                "iso_week" => 42,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2016,
                "month" => 10,
                "day" => 30,
                "full_date" => "2016-10-30",
                "day_of_year" => 304,
                "iso_week" => 43,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "October"
            ],
            [
                "year" => 2016,
                "month" => 11,
                "day" => 6,
                "full_date" => "2016-11-06",
                "day_of_year" => 311,
                "iso_week" => 44,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "November"
            ],
            [
                "year" => 2016,
                "month" => 11,
                "day" => 7,
                "full_date" => "2016-11-07",
                "day_of_year" => 312,
                "iso_week" => 45,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por el día de todos los Santos",
                "day_name" => "Monday",
                "month_name" => "November"
            ],
            [
                "year" => 2016,
                "month" => 11,
                "day" => 13,
                "full_date" => "2016-11-13",
                "day_of_year" => 318,
                "iso_week" => 45,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "November"
            ],
            [
                "year" => 2016,
                "month" => 11,
                "day" => 14,
                "full_date" => "2016-11-14",
                "day_of_year" => 319,
                "iso_week" => 46,
                "iso_day" => 1,
                "holiday_reason" => "Festivo por la Independencia de Cartagena",
                "day_name" => "Monday",
                "month_name" => "November"
            ],
            [
                "year" => 2016,
                "month" => 11,
                "day" => 20,
                "full_date" => "2016-11-20",
                "day_of_year" => 325,
                "iso_week" => 46,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "November"
            ],
            [
                "year" => 2016,
                "month" => 11,
                "day" => 27,
                "full_date" => "2016-11-27",
                "day_of_year" => 332,
                "iso_week" => 47,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "November"
            ],
            [
                "year" => 2016,
                "month" => 12,
                "day" => 4,
                "full_date" => "2016-12-04",
                "day_of_year" => 339,
                "iso_week" => 48,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "December"
            ],
            [
                "year" => 2016,
                "month" => 12,
                "day" => 8,
                "full_date" => "2016-12-08",
                "day_of_year" => 343,
                "iso_week" => 49,
                "iso_day" => 4,
                "holiday_reason" => "Inmaculada Concepción",
                "day_name" => "Thursday",
                "month_name" => "December"
            ],
            [
                "year" => 2016,
                "month" => 12,
                "day" => 11,
                "full_date" => "2016-12-11",
                "day_of_year" => 346,
                "iso_week" => 49,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "December"
            ],
            [
                "year" => 2016,
                "month" => 12,
                "day" => 18,
                "full_date" => "2016-12-18",
                "day_of_year" => 353,
                "iso_week" => 50,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "December"
            ],
            [
                "year" => 2016,
                "month" => 12,
                "day" => 25,
                "full_date" => "2016-12-25",
                "day_of_year" => 360,
                "iso_week" => 51,
                "iso_day" => 7,
                "holiday_reason" => "Día Domingo Festivo",
                "day_name" => "Sunday",
                "month_name" => "December"
            ]
        ];
    }
}