<?php

return [
    [
        'year'           => 2007,
        'month'          => 1,
        'day'            => 1,
        'full_date'      => '2007-01-01',
        'day_of_year'    => 1,
        'iso_week'       => 1,
        'iso_day'        => 1,
        'holiday_reason' => 'Año Nuevo',
        'day_name'       => 'Monday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2007,
        'month'          => 1,
        'day'            => 7,
        'full_date'      => '2007-01-07',
        'day_of_year'    => 7,
        'iso_week'       => 1,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2007,
        'month'          => 1,
        'day'            => 8,
        'full_date'      => '2007-01-08',
        'day_of_year'    => 8,
        'iso_week'       => 2,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de los Reyes Magos',
        'day_name'       => 'Monday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2007,
        'month'          => 1,
        'day'            => 14,
        'full_date'      => '2007-01-14',
        'day_of_year'    => 14,
        'iso_week'       => 2,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2007,
        'month'          => 1,
        'day'            => 21,
        'full_date'      => '2007-01-21',
        'day_of_year'    => 21,
        'iso_week'       => 3,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2007,
        'month'          => 1,
        'day'            => 28,
        'full_date'      => '2007-01-28',
        'day_of_year'    => 28,
        'iso_week'       => 4,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2007,
        'month'          => 2,
        'day'            => 4,
        'full_date'      => '2007-02-04',
        'day_of_year'    => 35,
        'iso_week'       => 5,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2007,
        'month'          => 2,
        'day'            => 11,
        'full_date'      => '2007-02-11',
        'day_of_year'    => 42,
        'iso_week'       => 6,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2007,
        'month'          => 2,
        'day'            => 18,
        'full_date'      => '2007-02-18',
        'day_of_year'    => 49,
        'iso_week'       => 7,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2007,
        'month'          => 2,
        'day'            => 25,
        'full_date'      => '2007-02-25',
        'day_of_year'    => 56,
        'iso_week'       => 8,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2007,
        'month'          => 3,
        'day'            => 4,
        'full_date'      => '2007-03-04',
        'day_of_year'    => 63,
        'iso_week'       => 9,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2007,
        'month'          => 3,
        'day'            => 11,
        'full_date'      => '2007-03-11',
        'day_of_year'    => 70,
        'iso_week'       => 10,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2007,
        'month'          => 3,
        'day'            => 18,
        'full_date'      => '2007-03-18',
        'day_of_year'    => 77,
        'iso_week'       => 11,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2007,
        'month'          => 3,
        'day'            => 19,
        'full_date'      => '2007-03-19',
        'day_of_year'    => 78,
        'iso_week'       => 12,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de San José',
        'day_name'       => 'Monday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2007,
        'month'          => 3,
        'day'            => 25,
        'full_date'      => '2007-03-25',
        'day_of_year'    => 84,
        'iso_week'       => 12,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2007,
        'month'          => 4,
        'day'            => 1,
        'full_date'      => '2007-04-01',
        'day_of_year'    => 91,
        'iso_week'       => 13,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2007,
        'month'          => 4,
        'day'            => 5,
        'full_date'      => '2007-04-05',
        'day_of_year'    => 95,
        'iso_week'       => 14,
        'iso_day'        => 4,
        'holiday_reason' => 'Jueves Santo',
        'day_name'       => 'Thursday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2007,
        'month'          => 4,
        'day'            => 6,
        'full_date'      => '2007-04-06',
        'day_of_year'    => 96,
        'iso_week'       => 14,
        'iso_day'        => 5,
        'holiday_reason' => 'Viernes Santo',
        'day_name'       => 'Friday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2007,
        'month'          => 4,
        'day'            => 8,
        'full_date'      => '2007-04-08',
        'day_of_year'    => 98,
        'iso_week'       => 14,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2007,
        'month'          => 4,
        'day'            => 15,
        'full_date'      => '2007-04-15',
        'day_of_year'    => 105,
        'iso_week'       => 15,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2007,
        'month'          => 4,
        'day'            => 22,
        'full_date'      => '2007-04-22',
        'day_of_year'    => 112,
        'iso_week'       => 16,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2007,
        'month'          => 4,
        'day'            => 29,
        'full_date'      => '2007-04-29',
        'day_of_year'    => 119,
        'iso_week'       => 17,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2007,
        'month'          => 5,
        'day'            => 1,
        'full_date'      => '2007-05-01',
        'day_of_year'    => 121,
        'iso_week'       => 18,
        'iso_day'        => 2,
        'holiday_reason' => 'Día del trabajo',
        'day_name'       => 'Tuesday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2007,
        'month'          => 5,
        'day'            => 6,
        'full_date'      => '2007-05-06',
        'day_of_year'    => 126,
        'iso_week'       => 18,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2007,
        'month'          => 5,
        'day'            => 13,
        'full_date'      => '2007-05-13',
        'day_of_year'    => 133,
        'iso_week'       => 19,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2007,
        'month'          => 5,
        'day'            => 20,
        'full_date'      => '2007-05-20',
        'day_of_year'    => 140,
        'iso_week'       => 20,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2007,
        'month'          => 5,
        'day'            => 21,
        'full_date'      => '2007-05-21',
        'day_of_year'    => 141,
        'iso_week'       => 21,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el Día de la Ascensión',
        'day_name'       => 'Monday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2007,
        'month'          => 5,
        'day'            => 27,
        'full_date'      => '2007-05-27',
        'day_of_year'    => 147,
        'iso_week'       => 21,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2007,
        'month'          => 6,
        'day'            => 3,
        'full_date'      => '2007-06-03',
        'day_of_year'    => 154,
        'iso_week'       => 22,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2007,
        'month'          => 6,
        'day'            => 10,
        'full_date'      => '2007-06-10',
        'day_of_year'    => 161,
        'iso_week'       => 23,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2007,
        'month'          => 6,
        'day'            => 11,
        'full_date'      => '2007-06-11',
        'day_of_year'    => 162,
        'iso_week'       => 24,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de Corpus Christi',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2007,
        'month'          => 6,
        'day'            => 17,
        'full_date'      => '2007-06-17',
        'day_of_year'    => 168,
        'iso_week'       => 24,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2007,
        'month'          => 6,
        'day'            => 18,
        'full_date'      => '2007-06-18',
        'day_of_year'    => 169,
        'iso_week'       => 25,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día del Sagrado Corazón de Jesús',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2007,
        'month'          => 6,
        'day'            => 24,
        'full_date'      => '2007-06-24',
        'day_of_year'    => 175,
        'iso_week'       => 25,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2007,
        'month'          => 7,
        'day'            => 1,
        'full_date'      => '2007-07-01',
        'day_of_year'    => 182,
        'iso_week'       => 26,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2007,
        'month'          => 7,
        'day'            => 2,
        'full_date'      => '2007-07-02',
        'day_of_year'    => 183,
        'iso_week'       => 27,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de San Pedro y San Pablo',
        'day_name'       => 'Monday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2007,
        'month'          => 7,
        'day'            => 8,
        'full_date'      => '2007-07-08',
        'day_of_year'    => 189,
        'iso_week'       => 27,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2007,
        'month'          => 7,
        'day'            => 15,
        'full_date'      => '2007-07-15',
        'day_of_year'    => 196,
        'iso_week'       => 28,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2007,
        'month'          => 7,
        'day'            => 20,
        'full_date'      => '2007-07-20',
        'day_of_year'    => 201,
        'iso_week'       => 29,
        'iso_day'        => 5,
        'holiday_reason' => 'Día de la independencia',
        'day_name'       => 'Friday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2007,
        'month'          => 7,
        'day'            => 22,
        'full_date'      => '2007-07-22',
        'day_of_year'    => 203,
        'iso_week'       => 29,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2007,
        'month'          => 7,
        'day'            => 29,
        'full_date'      => '2007-07-29',
        'day_of_year'    => 210,
        'iso_week'       => 30,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2007,
        'month'          => 8,
        'day'            => 5,
        'full_date'      => '2007-08-05',
        'day_of_year'    => 217,
        'iso_week'       => 31,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2007,
        'month'          => 8,
        'day'            => 7,
        'full_date'      => '2007-08-07',
        'day_of_year'    => 219,
        'iso_week'       => 32,
        'iso_day'        => 2,
        'holiday_reason' => 'Batalla de Boyacá',
        'day_name'       => 'Tuesday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2007,
        'month'          => 8,
        'day'            => 12,
        'full_date'      => '2007-08-12',
        'day_of_year'    => 224,
        'iso_week'       => 32,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2007,
        'month'          => 8,
        'day'            => 19,
        'full_date'      => '2007-08-19',
        'day_of_year'    => 231,
        'iso_week'       => 33,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2007,
        'month'          => 8,
        'day'            => 20,
        'full_date'      => '2007-08-20',
        'day_of_year'    => 232,
        'iso_week'       => 34,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por la Asunción de la Virgen',
        'day_name'       => 'Monday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2007,
        'month'          => 8,
        'day'            => 26,
        'full_date'      => '2007-08-26',
        'day_of_year'    => 238,
        'iso_week'       => 34,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2007,
        'month'          => 9,
        'day'            => 2,
        'full_date'      => '2007-09-02',
        'day_of_year'    => 245,
        'iso_week'       => 35,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2007,
        'month'          => 9,
        'day'            => 9,
        'full_date'      => '2007-09-09',
        'day_of_year'    => 252,
        'iso_week'       => 36,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2007,
        'month'          => 9,
        'day'            => 16,
        'full_date'      => '2007-09-16',
        'day_of_year'    => 259,
        'iso_week'       => 37,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2007,
        'month'          => 9,
        'day'            => 23,
        'full_date'      => '2007-09-23',
        'day_of_year'    => 266,
        'iso_week'       => 38,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2007,
        'month'          => 9,
        'day'            => 30,
        'full_date'      => '2007-09-30',
        'day_of_year'    => 273,
        'iso_week'       => 39,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2007,
        'month'          => 10,
        'day'            => 7,
        'full_date'      => '2007-10-07',
        'day_of_year'    => 280,
        'iso_week'       => 40,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2007,
        'month'          => 10,
        'day'            => 14,
        'full_date'      => '2007-10-14',
        'day_of_year'    => 287,
        'iso_week'       => 41,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2007,
        'month'          => 10,
        'day'            => 15,
        'full_date'      => '2007-10-15',
        'day_of_year'    => 288,
        'iso_week'       => 42,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el Día de la Raza',
        'day_name'       => 'Monday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2007,
        'month'          => 10,
        'day'            => 21,
        'full_date'      => '2007-10-21',
        'day_of_year'    => 294,
        'iso_week'       => 42,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2007,
        'month'          => 10,
        'day'            => 28,
        'full_date'      => '2007-10-28',
        'day_of_year'    => 301,
        'iso_week'       => 43,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2007,
        'month'          => 11,
        'day'            => 4,
        'full_date'      => '2007-11-04',
        'day_of_year'    => 308,
        'iso_week'       => 44,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2007,
        'month'          => 11,
        'day'            => 5,
        'full_date'      => '2007-11-05',
        'day_of_year'    => 309,
        'iso_week'       => 45,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de todos los Santos',
        'day_name'       => 'Monday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2007,
        'month'          => 11,
        'day'            => 11,
        'full_date'      => '2007-11-11',
        'day_of_year'    => 315,
        'iso_week'       => 45,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2007,
        'month'          => 11,
        'day'            => 12,
        'full_date'      => '2007-11-12',
        'day_of_year'    => 316,
        'iso_week'       => 46,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por la Independencia de Cartagena',
        'day_name'       => 'Monday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2007,
        'month'          => 11,
        'day'            => 18,
        'full_date'      => '2007-11-18',
        'day_of_year'    => 322,
        'iso_week'       => 46,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2007,
        'month'          => 11,
        'day'            => 25,
        'full_date'      => '2007-11-25',
        'day_of_year'    => 329,
        'iso_week'       => 47,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2007,
        'month'          => 12,
        'day'            => 2,
        'full_date'      => '2007-12-02',
        'day_of_year'    => 336,
        'iso_week'       => 48,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2007,
        'month'          => 12,
        'day'            => 8,
        'full_date'      => '2007-12-08',
        'day_of_year'    => 342,
        'iso_week'       => 49,
        'iso_day'        => 6,
        'holiday_reason' => 'Inmaculada Concepción',
        'day_name'       => 'Saturday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2007,
        'month'          => 12,
        'day'            => 9,
        'full_date'      => '2007-12-09',
        'day_of_year'    => 343,
        'iso_week'       => 49,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2007,
        'month'          => 12,
        'day'            => 16,
        'full_date'      => '2007-12-16',
        'day_of_year'    => 350,
        'iso_week'       => 50,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2007,
        'month'          => 12,
        'day'            => 23,
        'full_date'      => '2007-12-23',
        'day_of_year'    => 357,
        'iso_week'       => 51,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2007,
        'month'          => 12,
        'day'            => 25,
        'full_date'      => '2007-12-25',
        'day_of_year'    => 359,
        'iso_week'       => 52,
        'iso_day'        => 2,
        'holiday_reason' => 'Navidad',
        'day_name'       => 'Tuesday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2007,
        'month'          => 12,
        'day'            => 30,
        'full_date'      => '2007-12-30',
        'day_of_year'    => 364,
        'iso_week'       => 52,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
];
