<?php

return [
    [
        'year'           => 2021,
        'month'          => 1,
        'day'            => 1,
        'full_date'      => '2021-01-01',
        'day_of_year'    => 1,
        'iso_week'       => 53,
        'iso_day'        => 5,
        'holiday_reason' => 'Año Nuevo',
        'day_name'       => 'Friday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2021,
        'month'          => 1,
        'day'            => 3,
        'full_date'      => '2021-01-03',
        'day_of_year'    => 3,
        'iso_week'       => 53,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2021,
        'month'          => 1,
        'day'            => 10,
        'full_date'      => '2021-01-10',
        'day_of_year'    => 10,
        'iso_week'       => 1,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2021,
        'month'          => 1,
        'day'            => 11,
        'full_date'      => '2021-01-11',
        'day_of_year'    => 11,
        'iso_week'       => 2,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de los Reyes Magos',
        'day_name'       => 'Monday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2021,
        'month'          => 1,
        'day'            => 17,
        'full_date'      => '2021-01-17',
        'day_of_year'    => 17,
        'iso_week'       => 2,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2021,
        'month'          => 1,
        'day'            => 24,
        'full_date'      => '2021-01-24',
        'day_of_year'    => 24,
        'iso_week'       => 3,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2021,
        'month'          => 1,
        'day'            => 31,
        'full_date'      => '2021-01-31',
        'day_of_year'    => 31,
        'iso_week'       => 4,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2021,
        'month'          => 2,
        'day'            => 7,
        'full_date'      => '2021-02-07',
        'day_of_year'    => 38,
        'iso_week'       => 5,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2021,
        'month'          => 2,
        'day'            => 14,
        'full_date'      => '2021-02-14',
        'day_of_year'    => 45,
        'iso_week'       => 6,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2021,
        'month'          => 2,
        'day'            => 21,
        'full_date'      => '2021-02-21',
        'day_of_year'    => 52,
        'iso_week'       => 7,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2021,
        'month'          => 2,
        'day'            => 28,
        'full_date'      => '2021-02-28',
        'day_of_year'    => 59,
        'iso_week'       => 8,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2021,
        'month'          => 3,
        'day'            => 7,
        'full_date'      => '2021-03-07',
        'day_of_year'    => 66,
        'iso_week'       => 9,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2021,
        'month'          => 3,
        'day'            => 14,
        'full_date'      => '2021-03-14',
        'day_of_year'    => 73,
        'iso_week'       => 10,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2021,
        'month'          => 3,
        'day'            => 21,
        'full_date'      => '2021-03-21',
        'day_of_year'    => 80,
        'iso_week'       => 11,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2021,
        'month'          => 3,
        'day'            => 22,
        'full_date'      => '2021-03-22',
        'day_of_year'    => 81,
        'iso_week'       => 12,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de San José',
        'day_name'       => 'Monday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2021,
        'month'          => 3,
        'day'            => 28,
        'full_date'      => '2021-03-28',
        'day_of_year'    => 87,
        'iso_week'       => 12,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2021,
        'month'          => 4,
        'day'            => 1,
        'full_date'      => '2021-04-01',
        'day_of_year'    => 91,
        'iso_week'       => 13,
        'iso_day'        => 4,
        'holiday_reason' => 'Jueves Santo',
        'day_name'       => 'Thursday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2021,
        'month'          => 4,
        'day'            => 2,
        'full_date'      => '2021-04-02',
        'day_of_year'    => 92,
        'iso_week'       => 13,
        'iso_day'        => 5,
        'holiday_reason' => 'Viernes Santo',
        'day_name'       => 'Friday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2021,
        'month'          => 4,
        'day'            => 4,
        'full_date'      => '2021-04-04',
        'day_of_year'    => 94,
        'iso_week'       => 13,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2021,
        'month'          => 4,
        'day'            => 11,
        'full_date'      => '2021-04-11',
        'day_of_year'    => 101,
        'iso_week'       => 14,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2021,
        'month'          => 4,
        'day'            => 18,
        'full_date'      => '2021-04-18',
        'day_of_year'    => 108,
        'iso_week'       => 15,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2021,
        'month'          => 4,
        'day'            => 25,
        'full_date'      => '2021-04-25',
        'day_of_year'    => 115,
        'iso_week'       => 16,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2021,
        'month'          => 5,
        'day'            => 1,
        'full_date'      => '2021-05-01',
        'day_of_year'    => 121,
        'iso_week'       => 17,
        'iso_day'        => 6,
        'holiday_reason' => 'Día del trabajo',
        'day_name'       => 'Saturday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2021,
        'month'          => 5,
        'day'            => 2,
        'full_date'      => '2021-05-02',
        'day_of_year'    => 122,
        'iso_week'       => 17,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2021,
        'month'          => 5,
        'day'            => 9,
        'full_date'      => '2021-05-09',
        'day_of_year'    => 129,
        'iso_week'       => 18,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2021,
        'month'          => 5,
        'day'            => 16,
        'full_date'      => '2021-05-16',
        'day_of_year'    => 136,
        'iso_week'       => 19,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2021,
        'month'          => 5,
        'day'            => 17,
        'full_date'      => '2021-05-17',
        'day_of_year'    => 137,
        'iso_week'       => 20,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el Día de la Ascensión',
        'day_name'       => 'Monday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2021,
        'month'          => 5,
        'day'            => 23,
        'full_date'      => '2021-05-23',
        'day_of_year'    => 143,
        'iso_week'       => 20,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2021,
        'month'          => 5,
        'day'            => 30,
        'full_date'      => '2021-05-30',
        'day_of_year'    => 150,
        'iso_week'       => 21,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2021,
        'month'          => 6,
        'day'            => 6,
        'full_date'      => '2021-06-06',
        'day_of_year'    => 157,
        'iso_week'       => 22,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2021,
        'month'          => 6,
        'day'            => 7,
        'full_date'      => '2021-06-07',
        'day_of_year'    => 158,
        'iso_week'       => 23,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de Corpus Christi',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2021,
        'month'          => 6,
        'day'            => 13,
        'full_date'      => '2021-06-13',
        'day_of_year'    => 164,
        'iso_week'       => 23,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2021,
        'month'          => 6,
        'day'            => 14,
        'full_date'      => '2021-06-14',
        'day_of_year'    => 165,
        'iso_week'       => 24,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día del Sagrado Corazón de Jesús',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2021,
        'month'          => 6,
        'day'            => 20,
        'full_date'      => '2021-06-20',
        'day_of_year'    => 171,
        'iso_week'       => 24,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2021,
        'month'          => 6,
        'day'            => 27,
        'full_date'      => '2021-06-27',
        'day_of_year'    => 178,
        'iso_week'       => 25,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2021,
        'month'          => 7,
        'day'            => 4,
        'full_date'      => '2021-07-04',
        'day_of_year'    => 185,
        'iso_week'       => 26,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2021,
        'month'          => 7,
        'day'            => 5,
        'full_date'      => '2021-07-05',
        'day_of_year'    => 186,
        'iso_week'       => 27,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de San Pedro y San Pablo',
        'day_name'       => 'Monday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2021,
        'month'          => 7,
        'day'            => 11,
        'full_date'      => '2021-07-11',
        'day_of_year'    => 192,
        'iso_week'       => 27,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2021,
        'month'          => 7,
        'day'            => 18,
        'full_date'      => '2021-07-18',
        'day_of_year'    => 199,
        'iso_week'       => 28,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2021,
        'month'          => 7,
        'day'            => 20,
        'full_date'      => '2021-07-20',
        'day_of_year'    => 201,
        'iso_week'       => 29,
        'iso_day'        => 2,
        'holiday_reason' => 'Día de la independencia',
        'day_name'       => 'Tuesday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2021,
        'month'          => 7,
        'day'            => 25,
        'full_date'      => '2021-07-25',
        'day_of_year'    => 206,
        'iso_week'       => 29,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2021,
        'month'          => 8,
        'day'            => 1,
        'full_date'      => '2021-08-01',
        'day_of_year'    => 213,
        'iso_week'       => 30,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2021,
        'month'          => 8,
        'day'            => 7,
        'full_date'      => '2021-08-07',
        'day_of_year'    => 219,
        'iso_week'       => 31,
        'iso_day'        => 6,
        'holiday_reason' => 'Batalla de Boyacá',
        'day_name'       => 'Saturday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2021,
        'month'          => 8,
        'day'            => 8,
        'full_date'      => '2021-08-08',
        'day_of_year'    => 220,
        'iso_week'       => 31,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2021,
        'month'          => 8,
        'day'            => 15,
        'full_date'      => '2021-08-15',
        'day_of_year'    => 227,
        'iso_week'       => 32,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2021,
        'month'          => 8,
        'day'            => 16,
        'full_date'      => '2021-08-16',
        'day_of_year'    => 228,
        'iso_week'       => 33,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por la Asunción de la Virgen',
        'day_name'       => 'Monday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2021,
        'month'          => 8,
        'day'            => 22,
        'full_date'      => '2021-08-22',
        'day_of_year'    => 234,
        'iso_week'       => 33,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2021,
        'month'          => 8,
        'day'            => 29,
        'full_date'      => '2021-08-29',
        'day_of_year'    => 241,
        'iso_week'       => 34,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2021,
        'month'          => 9,
        'day'            => 5,
        'full_date'      => '2021-09-05',
        'day_of_year'    => 248,
        'iso_week'       => 35,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2021,
        'month'          => 9,
        'day'            => 12,
        'full_date'      => '2021-09-12',
        'day_of_year'    => 255,
        'iso_week'       => 36,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2021,
        'month'          => 9,
        'day'            => 19,
        'full_date'      => '2021-09-19',
        'day_of_year'    => 262,
        'iso_week'       => 37,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2021,
        'month'          => 9,
        'day'            => 26,
        'full_date'      => '2021-09-26',
        'day_of_year'    => 269,
        'iso_week'       => 38,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2021,
        'month'          => 10,
        'day'            => 3,
        'full_date'      => '2021-10-03',
        'day_of_year'    => 276,
        'iso_week'       => 39,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2021,
        'month'          => 10,
        'day'            => 10,
        'full_date'      => '2021-10-10',
        'day_of_year'    => 283,
        'iso_week'       => 40,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2021,
        'month'          => 10,
        'day'            => 17,
        'full_date'      => '2021-10-17',
        'day_of_year'    => 290,
        'iso_week'       => 41,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2021,
        'month'          => 10,
        'day'            => 18,
        'full_date'      => '2021-10-18',
        'day_of_year'    => 291,
        'iso_week'       => 42,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el Día de la Raza',
        'day_name'       => 'Monday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2021,
        'month'          => 10,
        'day'            => 24,
        'full_date'      => '2021-10-24',
        'day_of_year'    => 297,
        'iso_week'       => 42,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2021,
        'month'          => 10,
        'day'            => 31,
        'full_date'      => '2021-10-31',
        'day_of_year'    => 304,
        'iso_week'       => 43,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2021,
        'month'          => 11,
        'day'            => 1,
        'full_date'      => '2021-11-01',
        'day_of_year'    => 305,
        'iso_week'       => 44,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de todos los Santos',
        'day_name'       => 'Monday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2021,
        'month'          => 11,
        'day'            => 7,
        'full_date'      => '2021-11-07',
        'day_of_year'    => 311,
        'iso_week'       => 44,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2021,
        'month'          => 11,
        'day'            => 14,
        'full_date'      => '2021-11-14',
        'day_of_year'    => 318,
        'iso_week'       => 45,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2021,
        'month'          => 11,
        'day'            => 15,
        'full_date'      => '2021-11-15',
        'day_of_year'    => 319,
        'iso_week'       => 46,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por la Independencia de Cartagena',
        'day_name'       => 'Monday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2021,
        'month'          => 11,
        'day'            => 21,
        'full_date'      => '2021-11-21',
        'day_of_year'    => 325,
        'iso_week'       => 46,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2021,
        'month'          => 11,
        'day'            => 28,
        'full_date'      => '2021-11-28',
        'day_of_year'    => 332,
        'iso_week'       => 47,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2021,
        'month'          => 12,
        'day'            => 5,
        'full_date'      => '2021-12-05',
        'day_of_year'    => 339,
        'iso_week'       => 48,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2021,
        'month'          => 12,
        'day'            => 8,
        'full_date'      => '2021-12-08',
        'day_of_year'    => 342,
        'iso_week'       => 49,
        'iso_day'        => 3,
        'holiday_reason' => 'Inmaculada Concepción',
        'day_name'       => 'Wednesday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2021,
        'month'          => 12,
        'day'            => 12,
        'full_date'      => '2021-12-12',
        'day_of_year'    => 346,
        'iso_week'       => 49,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2021,
        'month'          => 12,
        'day'            => 19,
        'full_date'      => '2021-12-19',
        'day_of_year'    => 353,
        'iso_week'       => 50,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2021,
        'month'          => 12,
        'day'            => 25,
        'full_date'      => '2021-12-25',
        'day_of_year'    => 359,
        'iso_week'       => 51,
        'iso_day'        => 6,
        'holiday_reason' => 'Navidad',
        'day_name'       => 'Saturday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2021,
        'month'          => 12,
        'day'            => 26,
        'full_date'      => '2021-12-26',
        'day_of_year'    => 360,
        'iso_week'       => 51,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
];
