<?php

return [
    [
        'year'           => 2031,
        'month'          => 1,
        'day'            => 1,
        'full_date'      => '2031-01-01',
        'day_of_year'    => 1,
        'iso_week'       => 1,
        'iso_day'        => 3,
        'holiday_reason' => 'Año Nuevo',
        'day_name'       => 'Wednesday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2031,
        'month'          => 1,
        'day'            => 5,
        'full_date'      => '2031-01-05',
        'day_of_year'    => 5,
        'iso_week'       => 1,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2031,
        'month'          => 1,
        'day'            => 6,
        'full_date'      => '2031-01-06',
        'day_of_year'    => 6,
        'iso_week'       => 2,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de los Reyes Magos',
        'day_name'       => 'Monday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2031,
        'month'          => 1,
        'day'            => 12,
        'full_date'      => '2031-01-12',
        'day_of_year'    => 12,
        'iso_week'       => 2,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2031,
        'month'          => 1,
        'day'            => 19,
        'full_date'      => '2031-01-19',
        'day_of_year'    => 19,
        'iso_week'       => 3,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2031,
        'month'          => 1,
        'day'            => 26,
        'full_date'      => '2031-01-26',
        'day_of_year'    => 26,
        'iso_week'       => 4,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2031,
        'month'          => 2,
        'day'            => 2,
        'full_date'      => '2031-02-02',
        'day_of_year'    => 33,
        'iso_week'       => 5,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2031,
        'month'          => 2,
        'day'            => 9,
        'full_date'      => '2031-02-09',
        'day_of_year'    => 40,
        'iso_week'       => 6,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2031,
        'month'          => 2,
        'day'            => 16,
        'full_date'      => '2031-02-16',
        'day_of_year'    => 47,
        'iso_week'       => 7,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2031,
        'month'          => 2,
        'day'            => 23,
        'full_date'      => '2031-02-23',
        'day_of_year'    => 54,
        'iso_week'       => 8,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2031,
        'month'          => 3,
        'day'            => 2,
        'full_date'      => '2031-03-02',
        'day_of_year'    => 61,
        'iso_week'       => 9,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2031,
        'month'          => 3,
        'day'            => 9,
        'full_date'      => '2031-03-09',
        'day_of_year'    => 68,
        'iso_week'       => 10,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2031,
        'month'          => 3,
        'day'            => 16,
        'full_date'      => '2031-03-16',
        'day_of_year'    => 75,
        'iso_week'       => 11,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2031,
        'month'          => 3,
        'day'            => 23,
        'full_date'      => '2031-03-23',
        'day_of_year'    => 82,
        'iso_week'       => 12,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2031,
        'month'          => 3,
        'day'            => 24,
        'full_date'      => '2031-03-24',
        'day_of_year'    => 83,
        'iso_week'       => 13,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de San José',
        'day_name'       => 'Monday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2031,
        'month'          => 3,
        'day'            => 30,
        'full_date'      => '2031-03-30',
        'day_of_year'    => 89,
        'iso_week'       => 13,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2031,
        'month'          => 4,
        'day'            => 6,
        'full_date'      => '2031-04-06',
        'day_of_year'    => 96,
        'iso_week'       => 14,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2031,
        'month'          => 4,
        'day'            => 10,
        'full_date'      => '2031-04-10',
        'day_of_year'    => 100,
        'iso_week'       => 15,
        'iso_day'        => 4,
        'holiday_reason' => 'Jueves Santo',
        'day_name'       => 'Thursday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2031,
        'month'          => 4,
        'day'            => 11,
        'full_date'      => '2031-04-11',
        'day_of_year'    => 101,
        'iso_week'       => 15,
        'iso_day'        => 5,
        'holiday_reason' => 'Viernes Santo',
        'day_name'       => 'Friday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2031,
        'month'          => 4,
        'day'            => 13,
        'full_date'      => '2031-04-13',
        'day_of_year'    => 103,
        'iso_week'       => 15,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2031,
        'month'          => 4,
        'day'            => 20,
        'full_date'      => '2031-04-20',
        'day_of_year'    => 110,
        'iso_week'       => 16,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2031,
        'month'          => 4,
        'day'            => 27,
        'full_date'      => '2031-04-27',
        'day_of_year'    => 117,
        'iso_week'       => 17,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2031,
        'month'          => 5,
        'day'            => 1,
        'full_date'      => '2031-05-01',
        'day_of_year'    => 121,
        'iso_week'       => 18,
        'iso_day'        => 4,
        'holiday_reason' => 'Día del trabajo',
        'day_name'       => 'Thursday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2031,
        'month'          => 5,
        'day'            => 4,
        'full_date'      => '2031-05-04',
        'day_of_year'    => 124,
        'iso_week'       => 18,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2031,
        'month'          => 5,
        'day'            => 11,
        'full_date'      => '2031-05-11',
        'day_of_year'    => 131,
        'iso_week'       => 19,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2031,
        'month'          => 5,
        'day'            => 18,
        'full_date'      => '2031-05-18',
        'day_of_year'    => 138,
        'iso_week'       => 20,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2031,
        'month'          => 5,
        'day'            => 25,
        'full_date'      => '2031-05-25',
        'day_of_year'    => 145,
        'iso_week'       => 21,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2031,
        'month'          => 5,
        'day'            => 26,
        'full_date'      => '2031-05-26',
        'day_of_year'    => 146,
        'iso_week'       => 22,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el Día de la Ascensión',
        'day_name'       => 'Monday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2031,
        'month'          => 6,
        'day'            => 1,
        'full_date'      => '2031-06-01',
        'day_of_year'    => 152,
        'iso_week'       => 22,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2031,
        'month'          => 6,
        'day'            => 8,
        'full_date'      => '2031-06-08',
        'day_of_year'    => 159,
        'iso_week'       => 23,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2031,
        'month'          => 6,
        'day'            => 15,
        'full_date'      => '2031-06-15',
        'day_of_year'    => 166,
        'iso_week'       => 24,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2031,
        'month'          => 6,
        'day'            => 16,
        'full_date'      => '2031-06-16',
        'day_of_year'    => 167,
        'iso_week'       => 25,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de Corpus Christi',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2031,
        'month'          => 6,
        'day'            => 22,
        'full_date'      => '2031-06-22',
        'day_of_year'    => 173,
        'iso_week'       => 25,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2031,
        'month'          => 6,
        'day'            => 23,
        'full_date'      => '2031-06-23',
        'day_of_year'    => 174,
        'iso_week'       => 26,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día del Sagrado Corazón de Jesús',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2031,
        'month'          => 6,
        'day'            => 29,
        'full_date'      => '2031-06-29',
        'day_of_year'    => 180,
        'iso_week'       => 26,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2031,
        'month'          => 6,
        'day'            => 30,
        'full_date'      => '2031-06-30',
        'day_of_year'    => 181,
        'iso_week'       => 27,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de San Pedro y San Pablo',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2031,
        'month'          => 7,
        'day'            => 6,
        'full_date'      => '2031-07-06',
        'day_of_year'    => 187,
        'iso_week'       => 27,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2031,
        'month'          => 7,
        'day'            => 13,
        'full_date'      => '2031-07-13',
        'day_of_year'    => 194,
        'iso_week'       => 28,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2031,
        'month'          => 7,
        'day'            => 20,
        'full_date'      => '2031-07-20',
        'day_of_year'    => 201,
        'iso_week'       => 29,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2031,
        'month'          => 7,
        'day'            => 27,
        'full_date'      => '2031-07-27',
        'day_of_year'    => 208,
        'iso_week'       => 30,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2031,
        'month'          => 8,
        'day'            => 3,
        'full_date'      => '2031-08-03',
        'day_of_year'    => 215,
        'iso_week'       => 31,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2031,
        'month'          => 8,
        'day'            => 7,
        'full_date'      => '2031-08-07',
        'day_of_year'    => 219,
        'iso_week'       => 32,
        'iso_day'        => 4,
        'holiday_reason' => 'Batalla de Boyacá',
        'day_name'       => 'Thursday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2031,
        'month'          => 8,
        'day'            => 10,
        'full_date'      => '2031-08-10',
        'day_of_year'    => 222,
        'iso_week'       => 32,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2031,
        'month'          => 8,
        'day'            => 17,
        'full_date'      => '2031-08-17',
        'day_of_year'    => 229,
        'iso_week'       => 33,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2031,
        'month'          => 8,
        'day'            => 18,
        'full_date'      => '2031-08-18',
        'day_of_year'    => 230,
        'iso_week'       => 34,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por la Asunción de la Virgen',
        'day_name'       => 'Monday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2031,
        'month'          => 8,
        'day'            => 24,
        'full_date'      => '2031-08-24',
        'day_of_year'    => 236,
        'iso_week'       => 34,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2031,
        'month'          => 8,
        'day'            => 31,
        'full_date'      => '2031-08-31',
        'day_of_year'    => 243,
        'iso_week'       => 35,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2031,
        'month'          => 9,
        'day'            => 7,
        'full_date'      => '2031-09-07',
        'day_of_year'    => 250,
        'iso_week'       => 36,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2031,
        'month'          => 9,
        'day'            => 14,
        'full_date'      => '2031-09-14',
        'day_of_year'    => 257,
        'iso_week'       => 37,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2031,
        'month'          => 9,
        'day'            => 21,
        'full_date'      => '2031-09-21',
        'day_of_year'    => 264,
        'iso_week'       => 38,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2031,
        'month'          => 9,
        'day'            => 28,
        'full_date'      => '2031-09-28',
        'day_of_year'    => 271,
        'iso_week'       => 39,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2031,
        'month'          => 10,
        'day'            => 5,
        'full_date'      => '2031-10-05',
        'day_of_year'    => 278,
        'iso_week'       => 40,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2031,
        'month'          => 10,
        'day'            => 12,
        'full_date'      => '2031-10-12',
        'day_of_year'    => 285,
        'iso_week'       => 41,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2031,
        'month'          => 10,
        'day'            => 13,
        'full_date'      => '2031-10-13',
        'day_of_year'    => 286,
        'iso_week'       => 42,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el Día de la Raza',
        'day_name'       => 'Monday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2031,
        'month'          => 10,
        'day'            => 19,
        'full_date'      => '2031-10-19',
        'day_of_year'    => 292,
        'iso_week'       => 42,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2031,
        'month'          => 10,
        'day'            => 26,
        'full_date'      => '2031-10-26',
        'day_of_year'    => 299,
        'iso_week'       => 43,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2031,
        'month'          => 11,
        'day'            => 2,
        'full_date'      => '2031-11-02',
        'day_of_year'    => 306,
        'iso_week'       => 44,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2031,
        'month'          => 11,
        'day'            => 3,
        'full_date'      => '2031-11-03',
        'day_of_year'    => 307,
        'iso_week'       => 45,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de todos los Santos',
        'day_name'       => 'Monday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2031,
        'month'          => 11,
        'day'            => 9,
        'full_date'      => '2031-11-09',
        'day_of_year'    => 313,
        'iso_week'       => 45,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2031,
        'month'          => 11,
        'day'            => 16,
        'full_date'      => '2031-11-16',
        'day_of_year'    => 320,
        'iso_week'       => 46,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2031,
        'month'          => 11,
        'day'            => 17,
        'full_date'      => '2031-11-17',
        'day_of_year'    => 321,
        'iso_week'       => 47,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por la Independencia de Cartagena',
        'day_name'       => 'Monday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2031,
        'month'          => 11,
        'day'            => 23,
        'full_date'      => '2031-11-23',
        'day_of_year'    => 327,
        'iso_week'       => 47,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2031,
        'month'          => 11,
        'day'            => 30,
        'full_date'      => '2031-11-30',
        'day_of_year'    => 334,
        'iso_week'       => 48,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2031,
        'month'          => 12,
        'day'            => 7,
        'full_date'      => '2031-12-07',
        'day_of_year'    => 341,
        'iso_week'       => 49,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2031,
        'month'          => 12,
        'day'            => 8,
        'full_date'      => '2031-12-08',
        'day_of_year'    => 342,
        'iso_week'       => 50,
        'iso_day'        => 1,
        'holiday_reason' => 'Inmaculada Concepción',
        'day_name'       => 'Monday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2031,
        'month'          => 12,
        'day'            => 14,
        'full_date'      => '2031-12-14',
        'day_of_year'    => 348,
        'iso_week'       => 50,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2031,
        'month'          => 12,
        'day'            => 21,
        'full_date'      => '2031-12-21',
        'day_of_year'    => 355,
        'iso_week'       => 51,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2031,
        'month'          => 12,
        'day'            => 25,
        'full_date'      => '2031-12-25',
        'day_of_year'    => 359,
        'iso_week'       => 52,
        'iso_day'        => 4,
        'holiday_reason' => 'Navidad',
        'day_name'       => 'Thursday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2031,
        'month'          => 12,
        'day'            => 28,
        'full_date'      => '2031-12-28',
        'day_of_year'    => 362,
        'iso_week'       => 52,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
];