<?php

return [
    [
        'year'           => 2012,
        'month'          => 1,
        'day'            => 1,
        'full_date'      => '2012-01-01',
        'day_of_year'    => 1,
        'iso_week'       => 52,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2012,
        'month'          => 1,
        'day'            => 8,
        'full_date'      => '2012-01-08',
        'day_of_year'    => 8,
        'iso_week'       => 1,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2012,
        'month'          => 1,
        'day'            => 9,
        'full_date'      => '2012-01-09',
        'day_of_year'    => 9,
        'iso_week'       => 2,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de los Reyes Magos',
        'day_name'       => 'Monday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2012,
        'month'          => 1,
        'day'            => 15,
        'full_date'      => '2012-01-15',
        'day_of_year'    => 15,
        'iso_week'       => 2,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2012,
        'month'          => 1,
        'day'            => 22,
        'full_date'      => '2012-01-22',
        'day_of_year'    => 22,
        'iso_week'       => 3,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2012,
        'month'          => 1,
        'day'            => 29,
        'full_date'      => '2012-01-29',
        'day_of_year'    => 29,
        'iso_week'       => 4,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'January',
    ],
    [
        'year'           => 2012,
        'month'          => 2,
        'day'            => 5,
        'full_date'      => '2012-02-05',
        'day_of_year'    => 36,
        'iso_week'       => 5,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2012,
        'month'          => 2,
        'day'            => 12,
        'full_date'      => '2012-02-12',
        'day_of_year'    => 43,
        'iso_week'       => 6,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2012,
        'month'          => 2,
        'day'            => 19,
        'full_date'      => '2012-02-19',
        'day_of_year'    => 50,
        'iso_week'       => 7,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2012,
        'month'          => 2,
        'day'            => 26,
        'full_date'      => '2012-02-26',
        'day_of_year'    => 57,
        'iso_week'       => 8,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'February',
    ],
    [
        'year'           => 2012,
        'month'          => 3,
        'day'            => 4,
        'full_date'      => '2012-03-04',
        'day_of_year'    => 64,
        'iso_week'       => 9,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2012,
        'month'          => 3,
        'day'            => 11,
        'full_date'      => '2012-03-11',
        'day_of_year'    => 71,
        'iso_week'       => 10,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2012,
        'month'          => 3,
        'day'            => 18,
        'full_date'      => '2012-03-18',
        'day_of_year'    => 78,
        'iso_week'       => 11,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2012,
        'month'          => 3,
        'day'            => 19,
        'full_date'      => '2012-03-19',
        'day_of_year'    => 79,
        'iso_week'       => 12,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de San José',
        'day_name'       => 'Monday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2012,
        'month'          => 3,
        'day'            => 25,
        'full_date'      => '2012-03-25',
        'day_of_year'    => 85,
        'iso_week'       => 12,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'March',
    ],
    [
        'year'           => 2012,
        'month'          => 4,
        'day'            => 1,
        'full_date'      => '2012-04-01',
        'day_of_year'    => 92,
        'iso_week'       => 13,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2012,
        'month'          => 4,
        'day'            => 5,
        'full_date'      => '2012-04-05',
        'day_of_year'    => 96,
        'iso_week'       => 14,
        'iso_day'        => 4,
        'holiday_reason' => 'Jueves Santo',
        'day_name'       => 'Thursday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2012,
        'month'          => 4,
        'day'            => 6,
        'full_date'      => '2012-04-06',
        'day_of_year'    => 97,
        'iso_week'       => 14,
        'iso_day'        => 5,
        'holiday_reason' => 'Viernes Santo',
        'day_name'       => 'Friday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2012,
        'month'          => 4,
        'day'            => 8,
        'full_date'      => '2012-04-08',
        'day_of_year'    => 99,
        'iso_week'       => 14,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2012,
        'month'          => 4,
        'day'            => 15,
        'full_date'      => '2012-04-15',
        'day_of_year'    => 106,
        'iso_week'       => 15,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2012,
        'month'          => 4,
        'day'            => 22,
        'full_date'      => '2012-04-22',
        'day_of_year'    => 113,
        'iso_week'       => 16,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2012,
        'month'          => 4,
        'day'            => 29,
        'full_date'      => '2012-04-29',
        'day_of_year'    => 120,
        'iso_week'       => 17,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'April',
    ],
    [
        'year'           => 2012,
        'month'          => 5,
        'day'            => 1,
        'full_date'      => '2012-05-01',
        'day_of_year'    => 122,
        'iso_week'       => 18,
        'iso_day'        => 2,
        'holiday_reason' => 'Día del trabajo',
        'day_name'       => 'Tuesday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2012,
        'month'          => 5,
        'day'            => 6,
        'full_date'      => '2012-05-06',
        'day_of_year'    => 127,
        'iso_week'       => 18,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2012,
        'month'          => 5,
        'day'            => 13,
        'full_date'      => '2012-05-13',
        'day_of_year'    => 134,
        'iso_week'       => 19,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2012,
        'month'          => 5,
        'day'            => 20,
        'full_date'      => '2012-05-20',
        'day_of_year'    => 141,
        'iso_week'       => 20,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2012,
        'month'          => 5,
        'day'            => 21,
        'full_date'      => '2012-05-21',
        'day_of_year'    => 142,
        'iso_week'       => 21,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el Día de la Ascensión',
        'day_name'       => 'Monday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2012,
        'month'          => 5,
        'day'            => 27,
        'full_date'      => '2012-05-27',
        'day_of_year'    => 148,
        'iso_week'       => 21,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'May',
    ],
    [
        'year'           => 2012,
        'month'          => 6,
        'day'            => 3,
        'full_date'      => '2012-06-03',
        'day_of_year'    => 155,
        'iso_week'       => 22,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2012,
        'month'          => 6,
        'day'            => 10,
        'full_date'      => '2012-06-10',
        'day_of_year'    => 162,
        'iso_week'       => 23,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2012,
        'month'          => 6,
        'day'            => 11,
        'full_date'      => '2012-06-11',
        'day_of_year'    => 163,
        'iso_week'       => 24,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de Corpus Christi',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2012,
        'month'          => 6,
        'day'            => 17,
        'full_date'      => '2012-06-17',
        'day_of_year'    => 169,
        'iso_week'       => 24,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2012,
        'month'          => 6,
        'day'            => 18,
        'full_date'      => '2012-06-18',
        'day_of_year'    => 170,
        'iso_week'       => 25,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día del Sagrado Corazón de Jesús',
        'day_name'       => 'Monday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2012,
        'month'          => 6,
        'day'            => 24,
        'full_date'      => '2012-06-24',
        'day_of_year'    => 176,
        'iso_week'       => 25,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'June',
    ],
    [
        'year'           => 2012,
        'month'          => 7,
        'day'            => 1,
        'full_date'      => '2012-07-01',
        'day_of_year'    => 183,
        'iso_week'       => 26,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2012,
        'month'          => 7,
        'day'            => 2,
        'full_date'      => '2012-07-02',
        'day_of_year'    => 184,
        'iso_week'       => 27,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de San Pedro y San Pablo',
        'day_name'       => 'Monday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2012,
        'month'          => 7,
        'day'            => 8,
        'full_date'      => '2012-07-08',
        'day_of_year'    => 190,
        'iso_week'       => 27,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2012,
        'month'          => 7,
        'day'            => 15,
        'full_date'      => '2012-07-15',
        'day_of_year'    => 197,
        'iso_week'       => 28,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2012,
        'month'          => 7,
        'day'            => 20,
        'full_date'      => '2012-07-20',
        'day_of_year'    => 202,
        'iso_week'       => 29,
        'iso_day'        => 5,
        'holiday_reason' => 'Día de la independencia',
        'day_name'       => 'Friday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2012,
        'month'          => 7,
        'day'            => 22,
        'full_date'      => '2012-07-22',
        'day_of_year'    => 204,
        'iso_week'       => 29,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2012,
        'month'          => 7,
        'day'            => 29,
        'full_date'      => '2012-07-29',
        'day_of_year'    => 211,
        'iso_week'       => 30,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'July',
    ],
    [
        'year'           => 2012,
        'month'          => 8,
        'day'            => 5,
        'full_date'      => '2012-08-05',
        'day_of_year'    => 218,
        'iso_week'       => 31,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2012,
        'month'          => 8,
        'day'            => 7,
        'full_date'      => '2012-08-07',
        'day_of_year'    => 220,
        'iso_week'       => 32,
        'iso_day'        => 2,
        'holiday_reason' => 'Batalla de Boyacá',
        'day_name'       => 'Tuesday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2012,
        'month'          => 8,
        'day'            => 12,
        'full_date'      => '2012-08-12',
        'day_of_year'    => 225,
        'iso_week'       => 32,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2012,
        'month'          => 8,
        'day'            => 19,
        'full_date'      => '2012-08-19',
        'day_of_year'    => 232,
        'iso_week'       => 33,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2012,
        'month'          => 8,
        'day'            => 20,
        'full_date'      => '2012-08-20',
        'day_of_year'    => 233,
        'iso_week'       => 34,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por la Asunción de la Virgen',
        'day_name'       => 'Monday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2012,
        'month'          => 8,
        'day'            => 26,
        'full_date'      => '2012-08-26',
        'day_of_year'    => 239,
        'iso_week'       => 34,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'August',
    ],
    [
        'year'           => 2012,
        'month'          => 9,
        'day'            => 2,
        'full_date'      => '2012-09-02',
        'day_of_year'    => 246,
        'iso_week'       => 35,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2012,
        'month'          => 9,
        'day'            => 9,
        'full_date'      => '2012-09-09',
        'day_of_year'    => 253,
        'iso_week'       => 36,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2012,
        'month'          => 9,
        'day'            => 16,
        'full_date'      => '2012-09-16',
        'day_of_year'    => 260,
        'iso_week'       => 37,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2012,
        'month'          => 9,
        'day'            => 23,
        'full_date'      => '2012-09-23',
        'day_of_year'    => 267,
        'iso_week'       => 38,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2012,
        'month'          => 9,
        'day'            => 30,
        'full_date'      => '2012-09-30',
        'day_of_year'    => 274,
        'iso_week'       => 39,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'September',
    ],
    [
        'year'           => 2012,
        'month'          => 10,
        'day'            => 7,
        'full_date'      => '2012-10-07',
        'day_of_year'    => 281,
        'iso_week'       => 40,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2012,
        'month'          => 10,
        'day'            => 14,
        'full_date'      => '2012-10-14',
        'day_of_year'    => 288,
        'iso_week'       => 41,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2012,
        'month'          => 10,
        'day'            => 15,
        'full_date'      => '2012-10-15',
        'day_of_year'    => 289,
        'iso_week'       => 42,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el Día de la Raza',
        'day_name'       => 'Monday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2012,
        'month'          => 10,
        'day'            => 21,
        'full_date'      => '2012-10-21',
        'day_of_year'    => 295,
        'iso_week'       => 42,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2012,
        'month'          => 10,
        'day'            => 28,
        'full_date'      => '2012-10-28',
        'day_of_year'    => 302,
        'iso_week'       => 43,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'October',
    ],
    [
        'year'           => 2012,
        'month'          => 11,
        'day'            => 4,
        'full_date'      => '2012-11-04',
        'day_of_year'    => 309,
        'iso_week'       => 44,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2012,
        'month'          => 11,
        'day'            => 5,
        'full_date'      => '2012-11-05',
        'day_of_year'    => 310,
        'iso_week'       => 45,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por el día de todos los Santos',
        'day_name'       => 'Monday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2012,
        'month'          => 11,
        'day'            => 11,
        'full_date'      => '2012-11-11',
        'day_of_year'    => 316,
        'iso_week'       => 45,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2012,
        'month'          => 11,
        'day'            => 12,
        'full_date'      => '2012-11-12',
        'day_of_year'    => 317,
        'iso_week'       => 46,
        'iso_day'        => 1,
        'holiday_reason' => 'Festivo por la Independencia de Cartagena',
        'day_name'       => 'Monday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2012,
        'month'          => 11,
        'day'            => 18,
        'full_date'      => '2012-11-18',
        'day_of_year'    => 323,
        'iso_week'       => 46,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2012,
        'month'          => 11,
        'day'            => 25,
        'full_date'      => '2012-11-25',
        'day_of_year'    => 330,
        'iso_week'       => 47,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'November',
    ],
    [
        'year'           => 2012,
        'month'          => 12,
        'day'            => 2,
        'full_date'      => '2012-12-02',
        'day_of_year'    => 337,
        'iso_week'       => 48,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2012,
        'month'          => 12,
        'day'            => 8,
        'full_date'      => '2012-12-08',
        'day_of_year'    => 343,
        'iso_week'       => 49,
        'iso_day'        => 6,
        'holiday_reason' => 'Inmaculada Concepción',
        'day_name'       => 'Saturday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2012,
        'month'          => 12,
        'day'            => 9,
        'full_date'      => '2012-12-09',
        'day_of_year'    => 344,
        'iso_week'       => 49,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2012,
        'month'          => 12,
        'day'            => 16,
        'full_date'      => '2012-12-16',
        'day_of_year'    => 351,
        'iso_week'       => 50,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2012,
        'month'          => 12,
        'day'            => 23,
        'full_date'      => '2012-12-23',
        'day_of_year'    => 358,
        'iso_week'       => 51,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2012,
        'month'          => 12,
        'day'            => 25,
        'full_date'      => '2012-12-25',
        'day_of_year'    => 360,
        'iso_week'       => 52,
        'iso_day'        => 2,
        'holiday_reason' => 'Navidad',
        'day_name'       => 'Tuesday',
        'month_name'     => 'December',
    ],
    [
        'year'           => 2012,
        'month'          => 12,
        'day'            => 30,
        'full_date'      => '2012-12-30',
        'day_of_year'    => 365,
        'iso_week'       => 52,
        'iso_day'        => 7,
        'holiday_reason' => 'Día Domingo Festivo',
        'day_name'       => 'Sunday',
        'month_name'     => 'December',
    ],
];
